NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-proizvodnja2-dpp-podjetje-si-7054-ca-proizvodnja2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-proizvodnja2-dpp-podjetje-si-7054-ca-proizvodnja2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-proizvodnja2-dpp-podjetje-si-7054-ca-proizvodnja2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-proizvodnja2-dpp-podjetje-si-7054-ca-proizvodnja2.pem
    OrganizationalUnitIdentifier: orderer
